# Got help from piazza as well as chatpgt, prompt was how to install docker images for c++
FROM gcc:14.2
WORKDIR /app
COPY . /app
CMD ["/bin/sh", "-c", "g++ -o /app/code.out /app/code.cpp && /app/code.out"]